In [2]:
import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Using TensorFlow backend.

#### Import data & divide
- **X** = feature variables
- **y** = output

In [28]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [29]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Encode Catergorical Data
- one-hot encoding must be used for multi-class categorical data
- in this case, **Geography** at index 1 must one-hot enocded
- after the encoding, one dummy variable is removed to avoid falling into the "Dummy Variable trap"

In [71]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Feature - Geography
label_encoder_1 = LabelEncoder()
X[:, 1] = label_encoder_1.fit_transform( X[:, 1] )

# Feature - Gender
label_encoder_2 = LabelEncoder()
X[:, 2] = label_encoder_1.fit_transform( X[:, 2] )

one_hot = OneHotEncoder( categorical_features=[1] )
X = one_hot.fit_transform(X).toarray()

pd.DataFrame(X) # Note columns 0, 1, 2 - Three dummy variables for feature "Geography"

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,1.0,0.0,1.0,0.0,228.0,0.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88
1,0.0,1.0,0.0,1.0,1.0,217.0,0.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58
2,0.0,1.0,0.0,1.0,0.0,111.0,0.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57
3,0.0,1.0,0.0,1.0,0.0,308.0,0.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63
4,0.0,1.0,0.0,1.0,1.0,459.0,0.0,43.0,2.0,125510.82,1.0,1.0,1.0,79084.10
5,0.0,1.0,0.0,1.0,1.0,254.0,1.0,44.0,8.0,113755.78,2.0,1.0,0.0,149756.71
6,0.0,1.0,0.0,1.0,0.0,431.0,1.0,50.0,7.0,0.00,2.0,1.0,1.0,10062.80
7,1.0,0.0,1.0,0.0,0.0,8.0,0.0,29.0,4.0,115046.74,4.0,1.0,0.0,119346.88
8,0.0,1.0,0.0,1.0,0.0,110.0,1.0,44.0,4.0,142051.07,2.0,0.0,1.0,74940.50
9,0.0,1.0,0.0,1.0,0.0,293.0,1.0,27.0,2.0,134603.88,1.0,1.0,1.0,71725.73
10,0.0,1.0,0.0,1.0,0.0,137.0,1.0,31.0,6.0,102016.72,2.0,0.0,0.0,80181.12
11,0.0,1.0,0.0,1.0,1.0,106.0,1.0,24.0,3.0,0.00,2.0,1.0,0.0,76390.01
12,0.0,1.0,0.0,1.0,0.0,85.0,0.0,34.0,10.0,0.00,2.0,1.0,0.0,26260.98
13,0.0,1.0,0.0,1.0,0.0,158.0,0.0,25.0,5.0,0.00,2.0,0.0,0.0,190857.79
14,0.0,1.0,0.0,1.0,1.0,244.0,0.0,35.0,7.0,0.00,2.0,1.0,1.0,65951.65
15,1.0,0.0,1.0,0.0,0.0,225.0,1.0,45.0,3.0,143129.41,2.0,0.0,1.0,64327.26
16,1.0,0.0,1.0,0.0,0.0,262.0,1.0,58.0,1.0,132602.88,1.0,1.0,0.0,5097.67
17,0.0,1.0,0.0,1.0,1.0,158.0,0.0,24.0,9.0,0.00,2.0,1.0,1.0,14406.41
18,0.0,1.0,0.0,1.0,1.0,196.0,1.0,45.0,6.0,0.00,1.0,0.0,0.0,158684.81
19,0.0,1.0,0.0,1.0,0.0,335.0,0.0,24.0,6.0,0.00,2.0,1.0,1.0,54724.03
20,0.0,1.0,0.0,1.0,0.0,341.0,1.0,41.0,8.0,0.00,2.0,1.0,1.0,170886.17
21,0.0,1.0,0.0,1.0,1.0,245.0,0.0,32.0,8.0,0.00,2.0,1.0,0.0,138555.46
22,0.0,1.0,0.0,1.0,1.0,119.0,0.0,38.0,4.0,0.00,1.0,1.0,0.0,118913.53
23,0.0,1.0,0.0,1.0,0.0,278.0,1.0,46.0,3.0,0.00,2.0,0.0,1.0,8487.75
24,0.0,1.0,0.0,1.0,0.0,455.0,0.0,38.0,5.0,0.00,1.0,1.0,1.0,187616.16
25,0.0,1.0,0.0,1.0,0.0,186.0,1.0,25.0,3.0,0.00,2.0,0.0,1.0,124508.29
26,1.0,0.0,1.0,0.0,0.0,365.0,1.0,36.0,2.0,136815.64,1.0,1.0,1.0,170041.95
27,0.0,1.0,0.0,1.0,0.0,180.0,1.0,44.0,9.0,0.00,2.0,0.0,0.0,38433.35
28,1.0,0.0,1.0,0.0,0.0,183.0,0.0,43.0,3.0,141349.43,1.0,1.0,1.0,100187.43
29,0.0,1.0,0.0,1.0,0.0,20.0,1.0,29.0,0.0,59697.17,2.0,1.0,1.0,53483.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,0.0,1.0,0.0,1.0,0.0,127.0,1.0,42.0,7.0,151027.05,2.0,1.0,0.0,119377.36
9971,0.0,1.0,0.0,1.0,0.0,442.0,0.0,34.0,3.0,144751.81,1.0,0.0,0.0,166472.81
9972,0.0,1.0,0.0,1.0,0.0,367.0,1.0,26.0,4.0,155739.76,1.0,1.0,0.0,171552.02
9973,0.0,1.0,0.0,1.0,0.0,220.0,1.0,27.0,7.0,0.00,2.0,1.0,1.0,157474.10
9974,0.0,1.0,0.0,1.0,0.0,192.0,1.0,33.0,7.0,122531.86,1.0,1.0,0.0,13549.24
9975,1.0,0.0,1.0,0.0,0.0,219.0,1.0,50.0,1.0,113957.01,2.0,1.0,0.0,196526.55
9976,0.0,1.0,0.0,1.0,0.0,246.0,0.0,33.0,7.0,103377.81,1.0,1.0,0.0,84419.78
9977,0.0,1.0,0.0,1.0,0.0,292.0,0.0,32.0,9.0,0.00,2.0,1.0,1.0,24991.92
9978,0.0,1.0,0.0,1.0,0.0,383.0,1.0,40.0,9.0,93017.47,2.0,1.0,0.0,191608.97
9979,0.0,1.0,0.0,1.0,0.0,286.0,0.0,58.0,1.0,90022.85,1.0,0.0,1.0,2988.28
9980,0.0,1.0,0.0,1.0,1.0,350.0,1.0,35.0,6.0,74371.49,1.0,0.0,0.0,99595.67
9981,1.0,0.0,1.0,0.0,0.0,107.0,1.0,42.0,3.0,152039.70,1.0,1.0,1.0,53445.17
9982,1.0,0.0,1.0,0.0,0.0,264.0,0.0,46.0,7.0,137145.12,1.0,1.0,0.0,115146.40
9983,0.0,1.0,0.0,1.0,0.0,222.0,1.0,40.0,4.0,0.00,1.0,0.0,0.0,151325.24
9984,1.0,0.0,1.0,0.0,0.0,211.0,1.0,35.0,7.0,90602.42,2.0,1.0,1.0,51695.41
9985,0.0,1.0,0.0,1.0,0.0,268.0,1.0,36.0,6.0,123841.49,2.0,1.0,0.0,96833.00
9986,1.0,0.0,1.0,0.0,0.0,282.0,1.0,47.0,1.0,183579.54,2.0,0.0,1.0,34047.54
9987,0.0,1.0,0.0,1.0,1.0,215.0,1.0,30.0,8.0,180307.73,2.0,1.0,1.0,1914.41
9988,0.0,1.0,0.0,1.0,0.0,384.0,1.0,30.0,4.0,0.00,2.0,1.0,0.0,49337.84
9989,0.0,1.0,0.0,1.0,1.0,450.0,1.0,28.0,4.0,0.00,2.0,1.0,1.0,179436.60
9990,1.0,0.0,1.0,0.0,0.0,323.0,1.0,33.0,3.0,35016.60,1.0,1.0,0.0,53667.08
9991,0.0,1.0,0.0,1.0,0.0,206.0,0.0,53.0,4.0,88381.21,1.0,1.0,0.0,69384.71
9992,0.0,1.0,0.0,1.0,1.0,335.0,1.0,36.0,2.0,0.00,1.0,1.0,0.0,195192.40
9993,0.0,1.0,0.0,1.0,0.0,253.0,1.0,28.0,7.0,155060.41,1.0,1.0,0.0,29179.52
9994,0.0,1.0,0.0,1.0,0.0,409.0,0.0,29.0,2.0,0.00,2.0,0.0,0.0,167773.55
9995,0.0,1.0,0.0,1.0,0.0,380.0,1.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64
9996,0.0,1.0,0.0,1.0,0.0,125.0,1.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77
9997,0.0,1.0,0.0,1.0,0.0,318.0,0.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58
9998,1.0,0.0,1.0,0.0,0.0,381.0,1.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52
9999,0.0,1.0,0.0,1.0,0.0,401.0,0.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78

In [72]:
# Remove one dummy variable
X = X[:, 1:]
pd.DataFrame(X) # Note index 0, 1

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.0,0.0,1.0,0.0,228.0,0.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88
1,1.0,0.0,1.0,1.0,217.0,0.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58
2,1.0,0.0,1.0,0.0,111.0,0.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57
3,1.0,0.0,1.0,0.0,308.0,0.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63
4,1.0,0.0,1.0,1.0,459.0,0.0,43.0,2.0,125510.82,1.0,1.0,1.0,79084.10
5,1.0,0.0,1.0,1.0,254.0,1.0,44.0,8.0,113755.78,2.0,1.0,0.0,149756.71
6,1.0,0.0,1.0,0.0,431.0,1.0,50.0,7.0,0.00,2.0,1.0,1.0,10062.80
7,0.0,1.0,0.0,0.0,8.0,0.0,29.0,4.0,115046.74,4.0,1.0,0.0,119346.88
8,1.0,0.0,1.0,0.0,110.0,1.0,44.0,4.0,142051.07,2.0,0.0,1.0,74940.50
9,1.0,0.0,1.0,0.0,293.0,1.0,27.0,2.0,134603.88,1.0,1.0,1.0,71725.73
10,1.0,0.0,1.0,0.0,137.0,1.0,31.0,6.0,102016.72,2.0,0.0,0.0,80181.12
11,1.0,0.0,1.0,1.0,106.0,1.0,24.0,3.0,0.00,2.0,1.0,0.0,76390.01
12,1.0,0.0,1.0,0.0,85.0,0.0,34.0,10.0,0.00,2.0,1.0,0.0,26260.98
13,1.0,0.0,1.0,0.0,158.0,0.0,25.0,5.0,0.00,2.0,0.0,0.0,190857.79
14,1.0,0.0,1.0,1.0,244.0,0.0,35.0,7.0,0.00,2.0,1.0,1.0,65951.65
15,0.0,1.0,0.0,0.0,225.0,1.0,45.0,3.0,143129.41,2.0,0.0,1.0,64327.26
16,0.0,1.0,0.0,0.0,262.0,1.0,58.0,1.0,132602.88,1.0,1.0,0.0,5097.67
17,1.0,0.0,1.0,1.0,158.0,0.0,24.0,9.0,0.00,2.0,1.0,1.0,14406.41
18,1.0,0.0,1.0,1.0,196.0,1.0,45.0,6.0,0.00,1.0,0.0,0.0,158684.81
19,1.0,0.0,1.0,0.0,335.0,0.0,24.0,6.0,0.00,2.0,1.0,1.0,54724.03
20,1.0,0.0,1.0,0.0,341.0,1.0,41.0,8.0,0.00,2.0,1.0,1.0,170886.17
21,1.0,0.0,1.0,1.0,245.0,0.0,32.0,8.0,0.00,2.0,1.0,0.0,138555.46
22,1.0,0.0,1.0,1.0,119.0,0.0,38.0,4.0,0.00,1.0,1.0,0.0,118913.53
23,1.0,0.0,1.0,0.0,278.0,1.0,46.0,3.0,0.00,2.0,0.0,1.0,8487.75
24,1.0,0.0,1.0,0.0,455.0,0.0,38.0,5.0,0.00,1.0,1.0,1.0,187616.16
25,1.0,0.0,1.0,0.0,186.0,1.0,25.0,3.0,0.00,2.0,0.0,1.0,124508.29
26,0.0,1.0,0.0,0.0,365.0,1.0,36.0,2.0,136815.64,1.0,1.0,1.0,170041.95
27,1.0,0.0,1.0,0.0,180.0,1.0,44.0,9.0,0.00,2.0,0.0,0.0,38433.35
28,0.0,1.0,0.0,0.0,183.0,0.0,43.0,3.0,141349.43,1.0,1.0,1.0,100187.43
29,1.0,0.0,1.0,0.0,20.0,1.0,29.0,0.0,59697.17,2.0,1.0,1.0,53483.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,1.0,0.0,1.0,0.0,127.0,1.0,42.0,7.0,151027.05,2.0,1.0,0.0,119377.36
9971,1.0,0.0,1.0,0.0,442.0,0.0,34.0,3.0,144751.81,1.0,0.0,0.0,166472.81
9972,1.0,0.0,1.0,0.0,367.0,1.0,26.0,4.0,155739.76,1.0,1.0,0.0,171552.02
9973,1.0,0.0,1.0,0.0,220.0,1.0,27.0,7.0,0.00,2.0,1.0,1.0,157474.10
9974,1.0,0.0,1.0,0.0,192.0,1.0,33.0,7.0,122531.86,1.0,1.0,0.0,13549.24
9975,0.0,1.0,0.0,0.0,219.0,1.0,50.0,1.0,113957.01,2.0,1.0,0.0,196526.55
9976,1.0,0.0,1.0,0.0,246.0,0.0,33.0,7.0,103377.81,1.0,1.0,0.0,84419.78
9977,1.0,0.0,1.0,0.0,292.0,0.0,32.0,9.0,0.00,2.0,1.0,1.0,24991.92
9978,1.0,0.0,1.0,0.0,383.0,1.0,40.0,9.0,93017.47,2.0,1.0,0.0,191608.97
9979,1.0,0.0,1.0,0.0,286.0,0.0,58.0,1.0,90022.85,1.0,0.0,1.0,2988.28
9980,1.0,0.0,1.0,1.0,350.0,1.0,35.0,6.0,74371.49,1.0,0.0,0.0,99595.67
9981,0.0,1.0,0.0,0.0,107.0,1.0,42.0,3.0,152039.70,1.0,1.0,1.0,53445.17
9982,0.0,1.0,0.0,0.0,264.0,0.0,46.0,7.0,137145.12,1.0,1.0,0.0,115146.40
9983,1.0,0.0,1.0,0.0,222.0,1.0,40.0,4.0,0.00,1.0,0.0,0.0,151325.24
9984,0.0,1.0,0.0,0.0,211.0,1.0,35.0,7.0,90602.42,2.0,1.0,1.0,51695.41
9985,1.0,0.0,1.0,0.0,268.0,1.0,36.0,6.0,123841.49,2.0,1.0,0.0,96833.00
9986,0.0,1.0,0.0,0.0,282.0,1.0,47.0,1.0,183579.54,2.0,0.0,1.0,34047.54
9987,1.0,0.0,1.0,1.0,215.0,1.0,30.0,8.0,180307.73,2.0,1.0,1.0,1914.41
9988,1.0,0.0,1.0,0.0,384.0,1.0,30.0,4.0,0.00,2.0,1.0,0.0,49337.84
9989,1.0,0.0,1.0,1.0,450.0,1.0,28.0,4.0,0.00,2.0,1.0,1.0,179436.60
9990,0.0,1.0,0.0,0.0,323.0,1.0,33.0,3.0,35016.60,1.0,1.0,0.0,53667.08
9991,1.0,0.0,1.0,0.0,206.0,0.0,53.0,4.0,88381.21,1.0,1.0,0.0,69384.71
9992,1.0,0.0,1.0,1.0,335.0,1.0,36.0,2.0,0.00,1.0,1.0,0.0,195192.40
9993,1.0,0.0,1.0,0.0,253.0,1.0,28.0,7.0,155060.41,1.0,1.0,0.0,29179.52
9994,1.0,0.0,1.0,0.0,409.0,0.0,29.0,2.0,0.00,2.0,0.0,0.0,167773.55
9995,1.0,0.0,1.0,0.0,380.0,1.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64
9996,1.0,0.0,1.0,0.0,125.0,1.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77
9997,1.0,0.0,1.0,0.0,318.0,0.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58
9998,0.0,1.0,0.0,0.0,381.0,1.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52
9999,1.0,0.0,1.0,0.0,401.0,0.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78

#### Split into training and test set
- 80% : 20 %

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
list(map(len, (X_train, X_test, y_train, y_test )))

#### Feature Scaling

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_train)

Values before **standard scaling**

In [68]:
X_train

array([ 0.5698444 , -0.5698444 ,  0.5698444 ,  1.74309049,  0.1692298 ,
       -1.09168714, -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,
        0.64259497, -1.03227043,  1.10643166])

Values after **standard scaling**

In [43]:
X_train

array([[-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -1.75486502, -1.75486502, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -1.75486502, -1.75486502, ...,  0.64259497,
        -1.03227043,  0.32472465]])

#### The Sequential() model keeps all layers in track

In [56]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()

## Adding dense layers to our model

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
`activation` is the element-wise activation function
`kernel` is a weights matrix 
`bias` is a bias vector (only applicable if `use_bias` is `True`).

Note: if the input to the layer has a rank greater than 2, then
it is flattened prior to the initial dot product with `kernel`.

#### Example


    # as first layer in a sequential model:
    model = Sequential()
    model.add(Dense(32, input_shape=(16,)))
    # now the model will take as input arrays of shape (*, 16)
    # and output arrays of shape (*, 32)

    # after the first layer, you don't need to specify
    # the size of the input anymore:
    model.add(Dense(32))

#### Params
    input_shape : dim of inputs, MUST be list
    units: dimensionality of the output
    activation: Activation function to use, MUST be specified
    kernel_initializer: 'uniform'
    kernel_regularizer: Regularizer function applied to
    bias_regularizer: Regularizer function applied to the bias vector

In [57]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_shape = [11]))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

Compiling the model with:
- Optimizer: Adam optimizer 
- Loss function: binary cross entropy (as our output variable is binary)
- Metrics: accuracy (legacay metrics recall, precision cease to exist)

In [58]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the model with both training sets

In [59]:
classifier.fit(x = X_train, y = y_train, batch_size = 10, epochs = 100)

ValueError: Error when checking input: expected dense_8_input to have shape (None, 11) but got array with shape (8000, 13)

In [62]:
len(X_train)

13

In [146]:
y_pred = classifier.predict(X_test)

Notice all the output are probabilities from our sigmod funciton

In [147]:
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

We threshold all the values at 0.5

In [148]:
y_pred = y_pred > 0.5
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [151]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]

#### Predicitng from a single obeservation
- input must be [ [] ], as all inputs are 2D matrices
- must be scaled identically to the training data

In [163]:
to_predict = np.array([ [0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000] ])
to_predict = sc.fit_transform(to_predict) # Scaling

c:\nlp\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [1]:
classifier.predict( x = to_predict)

NameError: name 'classifier' is not defined

In [ ]:
new_prediction = classifier.predict( x = np.array())