In [1]:
import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Using TensorFlow backend.

#### Import data & divide
- **X** = feature variables
- **y** = output

In [166]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [167]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Encode Catergorical Data

In [168]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Feature - Geography
label_encoder_1 = LabelEncoder()
X[:, 1] = label_encoder_1.fit_transform( X[:, 1] )

# Feature - Gender
label_encoder_2 = LabelEncoder()
X[:, 2] = label_encoder_1.fit_transform( X[:, 2] )

one_hot = OneHotEncoder( categorical_features=[1] )
X = one_hot.fit_transform(X).toarray()

In [171]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

#### Split into training and test set
- 80% : 20 %

In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [145]:
list(map(len, (X_train, X_test, y_train, y_test )))

[8000, 2000, 8000, 2000]

#### Feature Scaling

In [80]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_train)

Values before **standard scaling**

In [78]:
X_train

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

Values after **standard scaling**

In [88]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

#### The Sequential() model keeps all layers in track

In [108]:
classifier = Sequential()

## Adding dense layers to our model

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
`activation` is the element-wise activation function
`kernel` is a weights matrix 
`bias` is a bias vector (only applicable if `use_bias` is `True`).

Note: if the input to the layer has a rank greater than 2, then
it is flattened prior to the initial dot product with `kernel`.

#### Example


    # as first layer in a sequential model:
    model = Sequential()
    model.add(Dense(32, input_shape=(16,)))
    # now the model will take as input arrays of shape (*, 16)
    # and output arrays of shape (*, 32)

    # after the first layer, you don't need to specify
    # the size of the input anymore:
    model.add(Dense(32))

#### Params
    input_shape : dim of inputs, MUST be list
    units: dimensionality of the output
    activation: Activation function to use, MUST be specified
    kernel_initializer: 'uniform'
    kernel_regularizer: Regularizer function applied to
    bias_regularizer: Regularizer function applied to the bias vector

In [109]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_shape = [12]))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

Compiling the model with:
- Optimizer: Adam optimizer 
- Loss function: binary cross entropy (as our output variable is binary)
- Metrics: accuracy (legacay metrics recall, precision cease to exist)

In [110]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the model with both training sets

In [111]:
classifier.fit(x = X_train, y = y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4782 - acc: 0.7957 2s - loss: 0.59
Epoch 2/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.4204 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4098 - acc: 0.8085
Epoch 4/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4003 - acc: 0.8274
Epoch 5/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3925 - acc: 0.8284
Epoch 6/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3869 - acc: 0.8275
Epoch 7/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3809 - acc: 0.8350
Epoch 8/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3762 - acc: 0.8420
Epoch 9/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3722 - acc: 0.8435
Epoch 10/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3692 - acc: 0.8485
Epoch 11/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3656 - acc: 0.8501
Epoch 12/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3633 - acc: 0.8519
Epoch 13/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3612 - acc: 0.8521
Epoch 14/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3606 - acc: 0.8529
Epoch 15/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3587 - acc: 0.8550
Epoch 16/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3577 - acc: 0.8536
Epoch 17/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3565 - acc: 0.8521
Epoch 18/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3568 - acc: 0.8557
Epoch 19/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3561 - acc: 0.8532
Epoch 20/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3538 - acc: 0.8559
Epoch 21/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3548 - acc: 0.8555
Epoch 22/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3541 - acc: 0.8580
Epoch 23/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3537 - acc: 0.8552
Epoch 24/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3520 - acc: 0.8577
Epoch 25/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3527 - acc: 0.8555
Epoch 26/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3526 - acc: 0.8571
Epoch 27/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3507 - acc: 0.8592
Epoch 28/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3512 - acc: 0.8577
Epoch 29/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3512 - acc: 0.8556
Epoch 30/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3499 - acc: 0.8582
Epoch 31/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3499 - acc: 0.8585
Epoch 32/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3504 - acc: 0.8577
Epoch 33/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3492 - acc: 0.8585
Epoch 34/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3487 - acc: 0.8579
Epoch 35/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3492 - acc: 0.8600
Epoch 36/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3486 - acc: 0.8574
Epoch 37/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3490 - acc: 0.8559
Epoch 38/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3482 - acc: 0.8582
Epoch 39/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3491 - acc: 0.8564
Epoch 40/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.3489 - acc: 0.8580
Epoch 41/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3486 - acc: 0.8575
Epoch 42/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3487 - acc: 0.8561
Epoch 43/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3474 - acc: 0.8589
Epoch 44/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3479 - acc: 0.8594
Epoch 45/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3476 - acc: 0.8586
Epoch 46/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3478 - acc: 0.8562
Epoch 47/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3465 - acc: 0.8594
Epoch 48/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3473 - acc: 0.8594
Epoch 49/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.3470 - acc: 0.8589
Epoch 50/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3461 - acc: 0.8591
Epoch 51/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3465 - acc: 0.8584
Epoch 52/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3470 - acc: 0.8595
Epoch 53/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3470 - acc: 0.8571
Epoch 54/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3475 - acc: 0.8586
Epoch 55/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3466 - acc: 0.8580
Epoch 56/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3462 - acc: 0.8572
Epoch 57/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3461 - acc: 0.8589
Epoch 58/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3458 - acc: 0.8611
Epoch 59/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3465 - acc: 0.8592
Epoch 60/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3470 - acc: 0.8589
Epoch 61/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3457 - acc: 0.8609
Epoch 62/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3465 - acc: 0.8602
Epoch 63/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3469 - acc: 0.8611
Epoch 64/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3458 - acc: 0.8585
Epoch 65/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3462 - acc: 0.8597
Epoch 66/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3462 - acc: 0.8604
Epoch 67/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3450 - acc: 0.8606
Epoch 68/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3453 - acc: 0.8605
Epoch 69/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3445 - acc: 0.8591
Epoch 70/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3448 - acc: 0.8589
Epoch 71/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.3452 - acc: 0.8610
Epoch 72/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3448 - acc: 0.8609
Epoch 73/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3445 - acc: 0.8584
Epoch 74/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3449 - acc: 0.8611
Epoch 75/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3446 - acc: 0.8601
Epoch 76/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3452 - acc: 0.8587
Epoch 77/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3455 - acc: 0.8601
Epoch 78/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3444 - acc: 0.8594
Epoch 79/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3447 - acc: 0.8597
Epoch 80/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3445 - acc: 0.8596
Epoch 81/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3438 - acc: 0.8607
Epoch 82/100

8000/8000 [==============================] - 1s 127us/step - loss: 0.3444 - acc: 0.8614
Epoch 83/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.3447 - acc: 0.8596
Epoch 84/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.3446 - acc: 0.8605
Epoch 85/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3443 - acc: 0.8584
Epoch 86/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3439 - acc: 0.8577
Epoch 87/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3444 - acc: 0.8610
Epoch 88/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3440 - acc: 0.8611
Epoch 89/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3439 - acc: 0.8600
Epoch 90/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3441 - acc: 0.8601
Epoch 91/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3436 - acc: 0.8614
Epoch 92/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3440 - acc: 0.8587
Epoch 93/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3439 - acc: 0.8604
Epoch 94/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3437 - acc: 0.8609
Epoch 95/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3431 - acc: 0.8589
Epoch 96/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3441 - acc: 0.8609
Epoch 97/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.3440 - acc: 0.8600
Epoch 98/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3431 - acc: 0.8607
Epoch 99/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3441 - acc: 0.8617
Epoch 100/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3430 - acc: 0.8581

In [146]:
y_pred = classifier.predict(X_test)

Notice all the output are probabilities from our sigmod funciton

In [147]:
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

We threshold all the values at 0.5

In [148]:
y_pred = y_pred > 0.5
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [151]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]

#### Predicitng from a single obeservation
- input must be [ [] ], as all inputs are 2D matrices
- must be scaled identically to the training data

In [163]:
to_predict = np.array([ [0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000] ])
to_predict = sc.fit_transform(to_predict) # Scaling

c:\nlp\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [165]:
classifier.predict( x = to_predict)

ValueError: Error when checking : expected dense_13_input to have shape (None, 12) but got array with shape (1, 10)

In [ ]:
new_prediction = classifier.predict( x = np.array())